name: Actividad1_Ingesta de datos

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.2"
      - name: paso1 - crea entorno virtual
        run: python -m venv venv
      - name: paso2 - activar entorno virtual
        run: ./venv/Scripts/activate
      - name: paso3 - actualizar pip
        run: pip install --upgrade pip
      - name: paso4 - instalar dependencias
        run: pip install -e .
      - name: paso5 - Realizar la ingesta de datos
        run: python src/bigdata/Ingesta.py
      - name: paso6 - Ejecutar script
        run: python script.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: generación informe prueba json
          commit_user_name: shara goez [GitHub Actions]
          commit_user_email: shara.mosquera@est.iudigital.edu.co
          commit_author: shara goez <shara.mosquera@est.iudigital.edu.co>
